### ISSUE TITLE
Missing ampersand (&) in /Library/Ruby/Gems/1.8/gems/bushido-0.0.25/lib/bushido/data.rb line 7

### ISSUE THREAD

**Issue by lezhangxyz** [sgrove/bushidogem#5]
Line 7 was originally
`def fire *hooks, data`
When it should be
`def fire *hooks, &data`

This was causing Locomotive's install script to crash.

**Comment by kevzettler** [comment]
this is fixed in 0.26 

bcb9c796cf974c7302738f7e48247466b6172a8c
